### ISSUE TITLE
Fork WSSoap with protected vars/methods

### ISSUE THREAD

**Issue by DarkGhostHunter** [TransbankDevelopers/transbank-sdk-php#45]
Currently,  [WSE-PHP](https://github.com/robrichards/wse-php) has protected properties and methods, which limits cleaner extensibility. 

I would suggest to fork the project, and change all properties and methods from private to protected to allow this.

I have already [submitted a pull request](https://github.com/robrichards/wse-php/pull/44) with these changes to the WSE-PHP package, but I doubt it will merged soon - the package hasn't received major updates since a year, top.

**Comment by LuisUrrutia** [comment]
@DarkGhostHunter the PR about change the properties to protected was done before by @gonzunigad creator of [freshworkstudio/transbank-web-services](https://github.com/freshworkstudio/transbank-web-services) (a cool library btw) because we were working on this issue too https://github.com/freshworkstudio/transbank-web-services/issues/18

Link to the PR: https://github.com/robrichards/wse-php/pull/41

And I also emailed Rob, but he's not responding, so I think we should take a different approach like the one I commented about in https://github.com/TransbankDevelopers/transbank-sdk-php/issues/39

PS: Rob is working on their libs, but I don't know what's going on with WSSE-PHP
https://github.com/robrichards/xmlseclibs/commit/d4ae595c50cbea494729126b2702282fea77be18

**Comment by DarkGhostHunter** [comment]
@LuisUrrutia Lol, didn't saw that PR. I cannot disagree with the approach "if you need features in a lib that is not actively maintained, you should fork it yourself".

From what I had read, the WSSOAP implementations for this SDK uses only some of the methods and it's not dependant on the whole library, so using what it's only necessary seems good.

**Comment by LuisUrrutia** [comment]
@DarkGhostHunter I thought the same because I've been trying to create a lib without php-soap extension (purely curl requests),  but in practice you have to take into account the security implications on building an XML and all the strict WSSE format.
Surely someone can do it, but it takes a long time and I'm not sure it's worth it, knowing that it will be deprecated in favor of REST.

**Comment by DarkGhostHunter** [comment]
@LuisUrrutia Didn't thought of how much time would take recreating that on cURL. Welp, at this point, I think it should suffice with extending what is necessary from the WSSE libs, stick to DRY, and let it rot in the tombs of PHP 5.

**Comment by DarkGhostHunter** [comment]
Gonna close this issue: it's been stale from almost a year and no real progress has been made.
